[versions]
app="0.0.1-SNAPSHOT"
spring-boot = "3.1.3"
kotlin = "1.9.10"
mysql="8.1.0"
poko="0.15.0"
springDependencyManagement="1.1.3"
h2db="2.2.222"

[plugins]
spring-boot = {id="org.springframework.boot", version.ref="spring-boot"}
kotlin-jvm = {id="org.jetbrains.kotlin.jvm", version.ref="kotlin"}
kotlin-spring = {id="org.jetbrains.kotlin.plugin.spring", version.ref="kotlin"}
kotlin-jpa = {id="org.jetbrains.kotlin.plugin.jpa", version.ref="kotlin"}
kotlin-allopen = {id="org.jetbrains.kotlin.jvm", version.ref="kotlin"}
spring-depManagement = {id="io.spring.dependency-management", version.ref="springDependencyManagement"}

[libraries]
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
poko = { module = "dev.drewhamilton.poko:poko-annotations", version.ref = "poko" }
db-h2 = { module = "com.h2database:h2", version.ref = "h2db" }
db-mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
kotlin-reflect = {module="org.jetbrains.kotlin:kotlin-reflect", version.ref="kotlin"}
spring-boot-test = {module="org.springframework.boot:spring-boot-starter-test", version.ref="spring-boot"}