[versions]
app = "0.0.1-SNAPSHOT"
spring-boot = "3.1.4" # https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
kotlin = "1.9.20-Beta2" # https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
kotlin-serialization = "1.6.0" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-core
mysql = "8.1.0" # https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
poko = "0.15.0" # https://mvnrepository.com/artifact/dev.drewhamilton.poko/poko-annotations
springDependencyManagement = "1.1.3" # https://mvnrepository.com/artifact/io.spring.dependency-management/io.spring.dependency-management.gradle.plugin
h2db = "2.2.224" # https://mvnrepository.com/artifact/com.h2database/h2
dokka = "1.9.0" # https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kmm = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-depManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[libraries]
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
poko = { module = "dev.drewhamilton.poko:poko-annotations", version.ref = "poko" }
db-h2 = { module = "com.h2database:h2", version.ref = "h2db" }
db-mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json ", version.ref = "kotlin-serialization" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }