services:
  db:
    image: mysql:9
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: developerDB
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  server:
    image: printing-house-server:0.0.2
    container_name: server
    links:
      - db
    environment:
      DB_DOMAIN: db
    restart: always
    ports:
      - :8080
  web-cli:
    image: web-cli:0.0.2
    container_name: web-cli
    links:
      - server
    restart: always
    ports:
      - 3000:80
volumes:
  dbdata:
